server.port=8081

# Conexión a la base de datos (Usando el nombre del servicio 'db' de docker-compose)
spring.datasource.url=jdbc:postgresql://db:5432/asistencia
spring.datasource.username=postgres
spring.datasource.password=postgres

# Persistencia: 'update' crea las tablas pero NO borra los datos existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización de datos (data.sql)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Mostrar las consultas SQL en la consola del contenedor para depurar
spring.jpa.show-sql=true